name: teste

on:
  workflow_dispatch:
  
  jobs:
    validade-voice:
      name: Voice Validation
      uses: daviolivas/teste-matrix-reusable/.github/workflows/matrix-reusable.yml@main
      secrets: inherit
