name: teste

on:
  workflow_dispatch:
  
jobs:
  validade-voice:
    strategy:
      matrix:
        machine: ${{ fromJson(vars.machines) }}
    name: Voice Validation
    uses: daviolivas/teste-matrix-reusable/.github/workflows/matrix-reusable.yml@main
    secrets: inherit
